---
deployment:
  tasks:
    - export DEPLOYPATH=home/bostanmo/puplic_html/subhan/repositories/vanillajs-materialize-todo-app	
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
